spring:
  application:
    name: api-gateway
  cloud:
    gateway:
      routes:
        - id: account-api
          uri: lb://account-api
          predicates:
            - Path=/auth/**, /users/**
        - id: task-api
          uri: lb://task-api
          predicates:
            - Path=/project/**, /task/**
      discovery:
        locator:
          enabled: true

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/

server:
  port: 8080
